### ISSUE TITLE
missing LCSI .  What is this? and how I could resolve this error?

### ISSUE THREAD

**Issue by sdsdjr** [jundongl/scikit-feature#16]
D:\prj>python findFeatures.py
Traceback (most recent call last):
  File "findFeatures.py", line 7, in <module>
    from skfeature.function.information_theoretical_based import MIM # infogain
  File "D:\ProgramData\Anaconda3\lib\site-packages\skfeature\function\information_theoretical_based\MIM.py", line 1, in <module>
    import LCSI
ModuleNotFoundError: No module named 'LCSI'

**Comment by bacalfa** [comment]
See https://github.com/bacalfa/scikit-feature/commit/f99c6bb5db4dddef233847dc5d4f33a2adac94a1
